### ISSUE TITLE
error No module named almathswig

### ISSUE THREAD

**Issue by 541380000** [aldebaran/libalmath#1]
I am using naoqi and python to program nao6 robot.
However, when I am running a motion example in the document, I need almath library. 
I installed it with: pip install almath
but when I.tried to import it, an error 'No module named  almathswig' occured and I have no idea how to fix it?
So anyone has some suggestions?

**Comment by victorpaleologue** [comment]
Hello, could you please detail your installation details, such as:
- operating system
- version of Python
- processor architecture

?

**Comment by RingaDinga01** [comment]
I am also having the exact same issue. 

My OS is WIN 10 64 Bit 
Using Python 2.7.18
Processor i5 7600k

**Comment by nnnanchen** [comment]
are you solve this problem...? I meet the same problem.

**Comment by 541380000** [comment]
Solved!
I am using it on  a robot with python2.7 and ubuntu.
I encountered this problem because of version.
The current version is too high. Please down-grade the package to have a try.

**Comment by 541380000** [comment]
> are you solve this problem...? I meet the same problem.

I added it comment. Please down-grade it to try

**Comment by RingaDinga01** [comment]
Do everything on a Linux system. Works a charm

**Comment by ruxandra-simioniuc** [comment]
> > are you solve this problem...? I meet the same problem.
> 
> I added it comment. Please down-grade it to try

can you say what to downgrade? I have the same problem and can't fix it.

**Comment by victorpaleologue** [comment]
> > > are you solve this problem...? I meet the same problem.
> > 
> > 
> > I added it comment. Please down-grade it to try
> 
> can you say what to downgrade? I have the same problem and can't fix it.

Perhaps you need Ubuntu 18.04...

**Comment by 541380000** [comment]
> > > are you solve this problem...? I meet the same problem.
> > 
> > 
> > I added it comment. Please down-grade it to try
> 
> can you say what to downgrade? I have the same problem and can't fix it.
down grade almath
type in your terminal:
`pip install almath==`
On my Ubuntu18.04, it print
`Collecting almath==
  Could not find a version that satisfies the requirement almath== (from versions: 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.12, 1.6.13, 1.6.14, 1.6.15, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.8.3)`
You can try to install a lower version like
`pip install almath==1.6.8`
I hope it may help you
